require("masteries")

--[[The mastery layout is in the following format: L1 L2 L3 L4 R1 R2 R3 R4]]
function Class(name, mastery_layout)
	return {
		Name = name,
		MasteryLayout = mastery_layout,
	}
end

function Exile(name, portraitname, class)
	if not portraitname then portraitname = name end
	return {
		Name = name,
		Class = class,
		Portrait = love.graphics.newImage("portraits/"..portraitname..".png"),
		Masteries = {},
		Talisman = nil,
	}
end

CLASS_CRONE = Class("Crone", {
	MASTERY_PYREDAMAGE, MASTERY_CAST, MASTERY_AURA, MASTERY_SPECIAL,
	MASTERY_PYREDAMAGE, MASTERY_STAMINA, MASTERY_SPEED, MASTERY_TAUNT,
})

CLASS_CUR = Class("Cur", {
	MASTERY_EVADE, MASTERY_SPRINT, MASTERY_RESPAWN, MASTERY_EVADE,
	MASTERY_PYREDAMAGE, MASTERY_CAST, MASTERY_BANISHMENT, MASTERY_SPECIAL,
})

CLASS_DEMON = Class("Demon", {
	MASTERY_SPRINT, MASTERY_EVADE, MASTERY_TAUNT, MASTERY_BALL,
	MASTERY_STAMINA, MASTERY_AURA, MASTERY_PYREHEALTH, MASTERY_BANISHMENT,
})

CLASS_HARP = Class("Harp", {
	MASTERY_EVADE, MASTERY_SPRINT, MASTERY_TAUNT, MASTERY_SPEED,
	MASTERY_BANISHMENT, MASTERY_CAST, MASTERY_RESPAWN, MASTERY_SPECIAL,
})

CLASS_IMP = Class("Imp", {
	MASTERY_SPEED, MASTERY_RESPAWN, MASTERY_BANISHMENT, MASTERY_PYREDAMAGE,
	MASTERY_SPECIAL, MASTERY_AURA, MASTERY_TAUNT, MASTERY_SPECIAL,
})

CLASS_NOMAD = Class("Nomad", {
	MASTERY_SPEED, MASTERY_CAST, MASTERY_EVADE, MASTERY_PYREHEALTH,
	MASTERY_STAMINA, MASTERY_BALL, MASTERY_RESPAWN, MASTERY_BANISHMENT,
})

CLASS_SAP = Class("Sap", {
	MASTERY_SPECIAL, MASTERY_AURA, MASTERY_CAST, MASTERY_BANISHMENT,
	MASTERY_PYREHEALTH, MASTERY_EVADE, MASTERY_RESPAWN, MASTERY_PYREHEALTH,
})

CLASS_SAVAGE = Class("Savage", {
	MASTERY_SPEED, MASTERY_EVADE, MASTERY_SPRINT, MASTERY_RESPAWN,
	MASTERY_CAST, MASTERY_BALL, MASTERY_TAUNT, MASTERY_SPECIAL,
})

CLASS_WYRM = Class("Wrym", {
	MASTERY_RESPAWN, MASTERY_TAUNT, MASTERY_SPEED, MASTERY_PYREDAMAGE,
	MASTERY_AURA, MASTERY_CAST, MASTERY_BANISHMENT, MASTERY_STAMINA,
})

CHAR_ALMER = Exile("Almer", nil, CLASS_SAVAGE)
CHAR_BARKER = Exile("Barker", nil, CLASS_CUR)
CHAR_BERTRUDE = Exile("Bertrude", nil, CLASS_CRONE)
CHAR_DALBERT = Exile("Dalbert", nil, CLASS_CUR)
CHAR_HEDWYN = Exile("Hedwyn", nil, CLASS_NOMAD)
CHAR_IGNARIUS = Exile("Ignarius", nil, CLASS_DEMON)
CHAR_JODARIEL = Exile("Jodariel", nil, CLASS_DEMON)
CHAR_LENDEL = Exile("Lendel", nil, CLASS_NOMAD)
CHAR_MAE = Exile("Mae", nil, CLASS_SAVAGE)
CHAR_MANLEY = Exile("Manley", nil, CLASS_SAP)
CHAR_MESSENGERIMP = Exile("Messenger-Imp", "MessengerImp", CLASS_IMP)
CHAR_ORALECH = Exile("Oralech", nil, CLASS_DEMON)
CHAR_PAMITHA = Exile("Pamitha", nil, CLASS_HARP)
CHAR_RUKEY = Exile("Rukey", nil, CLASS_CUR)
CHAR_SANDRA = Exile("Sandra", nil, CLASS_NOMAD)
CHAR_SIRDELUGE = Exile("Sir Deluge", "SirDeluge", CLASS_WYRM)
CHAR_SIRGILMAN = Exile("Sir Gilman", "SirGilman", CLASS_WYRM)
CHAR_TAMITHA = Exile("Tamitha", nil, CLASS_HARP)
CHAR_TIZO = Exile("Ti'zo", "Tizo", CLASS_IMP)
CHAR_UDMILDHE = Exile("Udmildhe", nil, CLASS_CRONE)
CHAR_VOLFRED = Exile("Volfred", nil, CLASS_SAP)

--[[This is the official ordering within the game.]]
CHARACTER_MAP = {
	[1]  = CHAR_HEDWYN,
	[2]  = CHAR_JODARIEL,
	[3]  = CHAR_RUKEY,
	[4]  = CHAR_MAE,
	[5]  = CHAR_TIZO,
	[6]  = CHAR_SIRGILMAN,
	[7]  = CHAR_PAMITHA,
	[8]  = CHAR_VOLFRED,
	[9]  = CHAR_BERTRUDE,
	[10] = CHAR_LENDEL,
	[11] = CHAR_IGNARIUS,
	[12] = CHAR_BARKER,
	[13] = CHAR_ALMER,
	[14] = CHAR_DALBERT,
	[15] = CHAR_SIRDELUGE,
	[16] = CHAR_TAMITHA,
	[17] = CHAR_MANLEY,
	[18] = CHAR_SANDRA,
	[19] = CHAR_ORALECH,
	[20] = CHAR_MESSENGERIMP,
	[21] = CHAR_UDMILDHE,
}
